import './globals.css'
import type { Metadata } from 'next'
import { Inter, Montserrat } from 'next/font/google'
import { Providers } from './redux/provider'


const inter = Inter({ subsets: ['latin'] })
const mont = Montserrat({subsets:['latin']})

export const metadata: Metadata = {
  title: 'Med Sync Solutions',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={mont.className}>
      <Providers>{children}</Providers>
      </body>
    </html>
  )
}
